### ISSUE TITLE
Error when accessing unset element with params

### ISSUE THREAD

**Issue by simonferndriger** [rehhouari/alpinejs-i18n#5]
In case you want to access translations dynamically without having to check/know if there is any translation or not, it is very useful to just use `$t(id) || 'Some static text'`. This works fine. However, when the translation requires parameters `$t(id, params)` there will be an error in case there is no translation available: `Alpine.js:423 Uncaught TypeError: Cannot read properties of undefined (reading 'replaceAll')`.

In my opinion it should work the same way, with or without params.

**Comment by rehhouari** [comment]
Hey im having trouble recreating this, how exactly are you setting up the translations? i tried using an empty string and a nonexistant key and in both cases `$t(id)` returns `id` instead of an empty string. and no error either when there are params.

**Comment by simonferndriger** [comment]
When I'm using `window.AlpineI18n.t(id)` it works, but when I'm using `window.AlpineI18n.t(id, params)` it throws the error on the translation element `en.home.title` where only `en.home` exists, but no title. Does that help?

**Comment by simonferndriger** [comment]
That's why currently I have to fix it by using `return window.AlpineI18n.t(id) ? window.AlpineI18n.t(id, params) : ''` as a wrapper

**Comment by simonferndriger** [comment]
I think I got it reproduced here: https://codepen.io/simonferndriger/pen/LYgZpob

**Comment by rehhouari** [comment]
hey sorry for the late reply, i think i fixed it in v2.4.0!
https://codepen.io/rehhouari/pen/jOerXNQ?editors=1111
let me know if it's still not fixed and thanks for submitting the issue ^^

**Comment by simonferndriger** [comment]
It Works perfectly, thanks!
