### ISSUE TITLE
AlpineI18n.locale does not refresh the translations as $locale does

### ISSUE THREAD

**Issue by simonferndriger** [rehhouari/alpinejs-i18n#7]
When using `$locale(...)` all the text gets refreshed. However, when using `AlpineI18n.locale = ...`, the value for `AlpineI18n.locale` gets actually changed, but the text stay the same...

**Comment by rehhouari** [comment]
hey thanks for the report!
after checking with the [example](https://alpinejs-i18n-example.vercel.app/) using devtools console and locally, it seems that its working normally for me [in this line](https://github.com/rehhouari/alpinejs-i18n-example/blob/3aeba27009a0a5b23a744d0ace11f03480cea7a2/index.html#L101)

can you provide reproduction steps or some errors, if any?

**Comment by simonferndriger** [comment]
Unfortunately, there were no errors, it just did not work. So I just switched to using `$locale()`...

**Comment by rehhouari** [comment]
sad to hear that, hopefully it's not that big of an incovenience!
feel free to re-open if you have more info on the matter.

**Comment by simonferndriger** [comment]
No worries, I figured out an easy way to use `$local()`, just wanted to let you know of this potential issue - but for the moment I think it's save to assume that it's not a big issue ;)
